name: Deploy multilingual React app to GitHub Pages

on:
  push:
    branches: ['master', 'english']  # Adicione outras branches aqui
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Fetch all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Traz todas as branches e histórico completo

      - name: Checkout Portuguese (master)
        uses: actions/checkout@v4
        with:
          ref: master
          path: pt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Build Portuguese site
        working-directory: ./pt
        run: |
          rm -rf build  # limpa build anterior
          npm ci
          npm run build
          rm -rf ../dist  # remove pasta dist anterior para garantir root limpo
          mkdir -p ../dist
          mv build/* ../dist/

      - name: Checkout English branch
        uses: actions/checkout@v4
        with:
          ref: english
          path: en

      - name: Build English site
        working-directory: ./en
        run: |
          rm -rf build  # limpa build anterior
          npm ci
          npm run build
          mkdir -p ../dist/en
          mv build/* ../dist/en/

      # Adicione outros idiomas abaixo com o mesmo padrão:
      # French
      # - name: Checkout French branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: french
      #     path: fr

      # - name: Build French site
      #   working-directory: ./fr
      #   run: |
      #     rm -rf build  # limpa build anterior
      #     npm ci
      #     npm run build
      #     mkdir -p ../dist/fr
      #     mv build/* ../dist/fr/

      # # Spanish
      # - name: Checkout Spanish branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: spanish
      #     path: es

      # - name: Build Spanish site
      #   working-directory: ./es
      #   run: |
      #     rm -rf build  # limpa build anterior
      #     npm ci
      #     npm run build
      #     mkdir -p ../dist/es
      #     mv build/* ../dist/es/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
